# Generated by Django 2.0.1 on 2018-01-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='slider_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='slider_step',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
    ]
