# Generated by Django 2.0.1 on 2018-01-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180118_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='number',
        ),
        migrations.AddField(
            model_name='appliance',
            name='label',
            field=models.CharField(default='fan', max_length=10),
        ),
    ]
