# Generated by Django 2.0.1 on 2018-01-19 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_auto_20180118_2118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliance',
            unique_together={('user', 'label')},
        ),
    ]
